name: pymodelcat
channels:
  - pypi
  - conda-forge
dependencies:
  - python=3.8.2
  - jupyter=1.0.0
  - pip=20.0.2
  - pip:
    - pandas==1.0.3
    - qgrid==1.3.1
    - git+git://github.com/skybristol/sciencebasepy@weblink_structured_data_crawler
